enum TEXTURE_CACHE_DATA {
    TEXTURE_CACHE_MODELID,
    TEXTURE_CACHE_TXD[MAX_TEXTURE_TXD+1 char],
    TEXTURE_CACHE_NAME[MAX_TEXTURE_NAME+1 char]
}

new g_TextureCache[MAX_TEXTURES][TEXTURE_CACHE_DATA];
