// Dialog ID's start at this number / offset
#define DIALOG_ID_OFFSET \
    1000

// Invalid ID
#define INVALID_DIALOG_ID \
    -1

// Dialog ID'S
enum {
    DIALOGID_OBJECT_MAIN = DIALOG_ID_OFFSET,
    DIALOGID_OBJECT_INDEX,
    DIALOGID_OBJECT_COORD,
    DIALOGID_OBJECT_COMMENT,
    DIALOGID_OBJECT_MATSIZE,
    DIALOGID_OBJECT_TEXT,
    DIALOGID_OBJECT_FONTSIZE,
    DIALOGID_COLORALPHA_TEXTURE,
    DIALOGID_COLORALPHA_FONTFACE,
    DIALOGID_COLORALPHA_ATTACH_1,
    DIALOGID_COLORALPHA_ATTACH_2,
    DIALOGID_VEHICLE_MAIN,
    DIALOGID_VEHICLE_COORD,
    DIALOGID_VEHICLE_COMMENT,
    DIALOGID_PICKUP_MAIN,
    DIALOGID_PICKUP_COORD,
    DIALOGID_PICKUP_COMMENT,
    DIALOGID_ATTACH_INDEXLIST,
    DIALOGID_ATTACH_MAIN,
    DIALOGID_ATTACH_BONE,
    DIALOGID_ATTACH_COORD,
    DIALOGID_ACTOR_MAIN,
    DIALOGID_ACTOR_COORD,
    DIALOGID_ACTOR_COMMENT,
    DIALOGID_ACTOR_ANIM_DELTA,
    DIALOGID_ACTOR_ANIM_TIME,
    DIALOGID_MAP_NEW,
    DIALOGID_MAP_SAVE_AS,
    DIALOGID_MAP_SAVE_CONFIRM,
    DIALOGID_MAP_LOAD,
    DIALOGID_MAPLIST,
    DIALOGID_MAPLIST_PAGE,
    DIALOGID_MAPLIST_SEARCH,
    DIALOGID_CATEGORYSELECT,
    DIALOGID_CATEGORYSELECT_PAGE,
    DIALOGID_CATEGORYSELECT_SEARCH,
    DIALOGID_SELECTLIST_PAGE,
    DIALOGID_SELECTLIST_SEARCH,
    DIALOGID_CREATELIST_PAGE,
    DIALOGID_CREATELIST_SEARCH,
    DIALOGID_TEXTURELIST_PAGE,
    DIALOGID_TEXTURELIST_SEARCH,
    DIALOGID_FONTLIST_PAGE,
    DIALOGID_FONTLIST_SEARCH,
    DIALOGID_COLORLIST_PAGE,
    DIALOGID_COLORLIST_SEARCH,
    DIALOGID_ANIMLIST_PAGE,
    DIALOGID_ANIMLIST_SEARCH,
    DIALOGID_CATMANAGER_CAT_CREATE,
    DIALOGID_CATMANAGER_CAT_DESTROY,
    DIALOGID_CATMANAGER_CAT_RENAME,
    DIALOGID_CATMANAGER_PAGE_ALL,
    DIALOGID_CATMANAGER_PAGE_CAT,
    DIALOGID_CATMANAGER_SEARCH_ALL,
    DIALOGID_CATMANAGER_SEARCH_CAT,
    DIALOGID_BUILDLIST_PAGE,
    DIALOGID_BUILDLIST_REMOVE,
    DIALOGID_BUILDLIST_RECREATE,
    MAX_DIALOGS
}

// Listitems for DIALOGID_OBJECT_MAIN
enum {
    LISTITEM_OBJECT_GOTO,
    LISTITEM_OBJECT_GET,
    LISTITEM_OBJECT_COORD,
    LISTITEM_OBJECT_MOVE,
    LISTITEM_OBJECT_ATTACH_SELECT,
    LISTITEM_OBJECT_ATTACH_APPLY,
    LISTITEM_OBJECT_ATTACH_REMOVE,
    LISTITEM_OBJECT_MATERIALS_COPY,
    LISTITEM_OBJECT_MATERIALS_PASTE,
    LISTITEM_OBJECT_DUPLICATE,
    LISTITEM_OBJECT_RECREATE,
    LISTITEM_OBJECT_REMOVE,
    LISTITEM_OBJECT_COMMENT,
    LISTITEM_OBJECT_COMMENT_RESET,
    LISTITEM_OBJECT_INDEX_START,
    LISTITEM_OBJECT_INDEX_END = (LISTITEM_OBJECT_INDEX_START + MAX_OBJECT_INDEX) - 1,
    MAX_LISTITEMS_OBJECT
}

// Listitems for DIALOGID_OBJECT_INDEX
enum {
    LISTITEM_OINDEX_REMOVE,          // Remove
    LISTITEM_OINDEX_MAT,             // Material: Texture
    LISTITEM_OINDEX_MAT_COLOR_S,     // Material: Color Select
    LISTITEM_OINDEX_MAT_COLOR_A,     // Material: Color Alpha
    LISTITEM_OINDEX_MAT_COLOR_R,     // Material: Color Reset
    LISTITEM_OINDEX_TXT,             // Text:
    LISTITEM_OINDEX_TXT_MATSIZE,     // Text: Material Size
    LISTITEM_OINDEX_TXT_FONTFACE,    // Text: Font Face
    LISTITEM_OINDEX_TXT_FONTSIZE,    // Text: Font Size
    LISTITEM_OINDEX_TXT_ISBOLD,      // Text: Is Bold
    LISTITEM_OINDEX_TXT_ALIGN,       // Text: Alignment
    LISTITEM_OINDEX_TXT_FONTCOLOR_S, // Text: Font Color Select
    LISTITEM_OINDEX_TXT_FONTCOLOR_A, // Text: Font Color Alpha
    LISTITEM_OINDEX_TXT_BACKCOLOR_S, // Text: Background Color Select
    LISTITEM_OINDEX_TXT_BACKCOLOR_O, // Text: Background Color Opaque
    LISTITEM_OINDEX_TXT_BACKCOLOR_T, // Text: Background Color Transparent
    MAX_LISTITEMS_OINDEX
}

// Listitems for DIALOGID_VEHICLE_MAIN
enum {
    LISTITEM_VEHICLE_GOTO,
    LISTITEM_VEHICLE_GET,
    LISTITEM_VEHICLE_DRIVE,
    LISTITEM_VEHICLE_COORD,
    LISTITEM_VEHICLE_MOVE,
    LISTITEM_VEHICLE_ATTACH,
    LISTITEM_VEHICLE_DUPLICATE,
    LISTITEM_VEHICLE_RECREATE,
    LISTITEM_VEHICLE_REMOVE,
    LISTITEM_VEHICLE_COMMENT,
    LISTITEM_VEHICLE_COMMENT_RESET,
    LISTITEM_VEHICLE_COLOR1,
    LISTITEM_VEHICLE_COLOR2,
    LISTITEM_VEHICLE_MODSHOP,
    LISTITEM_VEHICLE_REMOVEMODS,
    MAX_LISTITEMS_VEHICLE
}

// Listitems for DIALOGID_PICKUP_MAIN
enum {
    LISTITEM_PICKUP_GOTO,
    LISTITEM_PICKUP_GET,
    LISTITEM_PICKUP_COORD,
    LISTITEM_PICKUP_MOVE,
    LISTITEM_PICKUP_REMOVE,
    LISTITEM_PICKUP_DUPLICATE,
    LISTITEM_PICKUP_COMMENT,
    LISTITEM_PICKUP_COMMENT_RESET,
    MAX_LISTITEMS_PICKUP
}

// Listitems for DIALOGID_ATTACH_MAIN
enum {
    LISTITEM_ATTACH_MODEL,
    LISTITEM_ATTACH_BONE,
    LISTITEM_ATTACH_COORD,
    LISTITEM_ATTACH_MOVE,
    LISTITEM_ATTACH_COLOR1,
    LISTITEM_ATTACH_ALPHA1,
    LISTITEM_ATTACH_COLOR2,
    LISTITEM_ATTACH_ALPHA2,
    LISTITEM_ATTACH_REMOVE,
    MAX_LISTITEMS_ATTACH
}

// Listitems for DIALOGID_ACTOR_MAIN
enum {
    LISTITEM_ACTOR_GOTO,
    LISTITEM_ACTOR_GET,
    LISTITEM_ACTOR_COORD,
    LISTITEM_ACTOR_MOVE,
    LISTITEM_ACTOR_REMOVE,
    LISTITEM_ACTOR_DUPLICATE,
    LISTITEM_ACTOR_COMMENT,
    LISTITEM_ACTOR_COMMENT_RESET,
    LISTITEM_ACTOR_ANIM_INDEX,
    LISTITEM_ACTOR_ANIM_DELTA,
    LISTITEM_ACTOR_ANIM_LOOP,
    LISTITEM_ACTOR_ANIM_LOCKX,
    LISTITEM_ACTOR_ANIM_LOCKY,
    LISTITEM_ACTOR_ANIM_FREEZE,
    LISTITEM_ACTOR_ANIM_TIME,
    LISTITEM_ACTOR_ANIM_UPDATE,
    LISTITEM_ACTOR_ANIM_REMOVE,
    MAX_LISTITEMS_ACTOR
}
