#define BUILDING_DATA_SIZE \
    44763

#define INVALID_BUILDING_ID \
    -1

#define MIN_BUILDING_ID \
    0

#define MAX_BUILDING_ID \
    BUILDING_DATA_SIZE-1

#define REMOVE_BUILDING_RANGE \
    0.1

#define INVALID_BUILDING_LODMODEL \
    0xFFFF

enum {
    BUILDING_INCMODE_ALL,
    BUILDING_INCMODE_REMOVED,
    BUILDING_INCMODE_EXISTING
}
