enum BUILDING_DATA {
           BUILDING_DATA_MODEL,
           BUILDING_DATA_LODMODEL,
    Float: BUILDING_DATA_X,
    Float: BUILDING_DATA_Y,
    Float: BUILDING_DATA_Z,
    Float: BUILDING_DATA_RX,
    Float: BUILDING_DATA_RY,
    Float: BUILDING_DATA_RZ,
    Float: BUILDING_DATA_OFFSET,
    bool:  BUILDING_DATA_ISLOADED,
    bool:  BUILDING_DATA_ISREMOVED
}

new
    g_BuildingData[BUILDING_DATA_SIZE][BUILDING_DATA]
;
