enum {
	Text: FONTLIST_GTD_BG,
	Text: FONTLIST_GTD_CLOSE,
	Text: FONTLIST_GTD_PAGE_F,
	Text: FONTLIST_GTD_PAGE_P,
	Text: FONTLIST_GTD_PAGE_N,
	Text: FONTLIST_GTD_PAGE_L,
	MAX_FONTLIST_GTDS
}

enum {
	PlayerText: FONTLIST_PTD_CAPTION,
	PlayerText: FONTLIST_PTD_PAGE,
	PlayerText: FONTLIST_PTD_SEARCH,
	PlayerText: FONTLIST_PTD_ROW[MAX_FONTLIST_ROWS],
	MAX_FONTLIST_PTDS
}

enum {
	FONTLIST_DATA_PAGE,
	FONTLIST_DATA_MAXPAGE,
	FONTLIST_DATA_APPLIED_ROW,
	FONTLIST_DATA_SEARCH[MAX_SEARCH_LEN+1 char],
	FONTLIST_DATA_ROW_FONTID[MAX_FONTLIST_ROWS],
	MAX_FONTLIST_DATA
}

new
	Text:       g_FontListGTD[MAX_FONTLIST_GTDS],
	PlayerText: g_FontListPTD[MAX_PLAYERS][MAX_FONTLIST_PTDS],
	            g_FontListData[MAX_PLAYERS][MAX_FONTLIST_DATA]
;
