enum CATEGORYSELECT_DATA {
    CATEGORYSELECT_PAGE,
    CATEGORYSELECT_MAXPAGE,
    CATEGORYSELECT_SEARCH[MAX_SEARCH_LEN+1 char],
    CATEGORYSELECT_ROW_ID[MAX_CATEGORYSELECT_ROWS]
}

new g_CategorySelectData[MAX_PLAYERS][CATEGORYSELECT_DATA];
