#define OFFSETEDIT_UPDATE_INTERVAL \
    100 // ms

#define OFFSETEDIT_MULTIPLIER_ADD \
    0.02

#define OFFSETEDIT_MULTIPLIER_LIMIT \
    1.0

#define OFFSETEDIT_MOVE_SLOW \
    0.5

#define OFFSETEDIT_MOVE_NORMAL \
    1.0

enum {
    OFFSETEDIT_MODE_X,
    OFFSETEDIT_MODE_Y,
    OFFSETEDIT_MODE_Z,
    OFFSETEDIT_MODE_RX,
    OFFSETEDIT_MODE_RY,
    OFFSETEDIT_MODE_RZ
}
