enum VEHICLE_DATA {
    Float: VEHICLE_DATA_MEMORY_X,
    Float: VEHICLE_DATA_MEMORY_Y,
    Float: VEHICLE_DATA_MEMORY_Z,
    Float: VEHICLE_DATA_MEMORY_RZ,
           VEHICLE_DATA_COLOR_1,
           VEHICLE_DATA_COLOR_2,
           VEHICLE_DATA_PAINTJOB,
           VEHICLE_DATA_COMMENT[MAX_COMMENT_LEN+1 char],
    bool:  VEHICLE_DATA_MODTP_TOGGLE,
    Float: VEHICLE_DATA_MODTP_X,
    Float: VEHICLE_DATA_MODTP_Y,
    Float: VEHICLE_DATA_MODTP_Z,
    Float: VEHICLE_DATA_MODTP_A
}

new g_VehicleData[MAX_VEHICLES][VEHICLE_DATA];
