enum {
    HELP_KEYBIND_OFFEDIT_ADD,  // KEY_ANALOG_RIGHT
    HELP_KEYBIND_OFFEDIT_SUB,  // KEY_ANALOG_LEFT
    HELP_KEYBIND_OFFEDIT_MODE, // KEY_SPRINT
    HELP_KEYBIND_OFFEDIT_SLOW, // KEY_WALK
    HELP_KEYBIND_CAM_FORWARD,  // Up Key
    HELP_KEYBIND_CAM_BACK,     // Down Key
    HELP_KEYBIND_CAM_LEFT,     // Left Key
    HELP_KEYBIND_CAM_RIGHT,    // Right Key
    HELP_KEYBIND_CAM_FAST,     // KEY_JUMP
    HELP_KEYBIND_CAM_SLOW,     // KEY_WALK
    HELP_KEYBIND_MOUSE_ON,     // KEY_YES / KEY_CROUCH
    HELP_KEYBIND_MOUSE_OFF,    // ESC
    HELP_KEYBIND_EDIT_LOOK,    // KEY_SPRINT
    MAX_HELP_KEYBINDS
}

enum {
    HELP_CREDIT_AUTHOR,
    HELP_CREDIT_TDEDIT,
    HELP_CREDIT_TEXTURES,
    HELP_CREDIT_BUILDINGS,
    HELP_CREDIT_MODELNAMES,
    HELP_CREDIT_MODELSIZES,
    HELP_CREDIT_CAMMODE,
    HELP_CREDIT_STRLIB,
    HELP_CREDIT_SSCANF,
    HELP_CREDIT_SKINNAMES,
    HELP_CREDIT_ATTACHOBJPOS,
    MAX_HELP_CREDITS
}
