enum {
    Text: HELP_GTD_BG,
    Text: HELP_GTD_CLOSE,
    Text: HELP_GTD_CAPTION,

    Text: HELP_GTD_INFO_TAB,
    Text: HELP_GTD_INFO_CAPTION,
    Text: HELP_GTD_INFO_CONTENT,

    Text: HELP_GTD_KEYBIND_TAB,
    Text: HELP_GTD_KEYBIND_CAPTION,
    Text: HELP_GTD_KEYBIND_L[MAX_HELP_KEYBINDS],
    Text: HELP_GTD_KEYBIND_C[MAX_HELP_KEYBINDS],
    Text: HELP_GTD_KEYBIND_R[MAX_HELP_KEYBINDS],

    Text: HELP_GTD_CREDIT_TAB,
    Text: HELP_GTD_CREDIT_CAPTION,
    Text: HELP_GTD_CREDIT_L[MAX_HELP_CREDITS],
    Text: HELP_GTD_CREDIT_C[MAX_HELP_CREDITS],
    Text: HELP_GTD_CREDIT_R[MAX_HELP_CREDITS],
          MAX_HELP_GTDS
}

new Text: g_HelpGTD[MAX_HELP_GTDS];
